version = 0.1

[default.deploy.parameters]
stack_name = "anchor-v0-analytics"
resolve_s3 = true
s3_prefix = "anchor-v0-analytics"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Region=\"us-east-1\" SecretId=\"anchor/v0/app-config\""
image_repositories = []
profile = "anchor"

[default.global.parameters]
region = "us-east-1"
